- name: Install Tools and Generate Code
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          
          export PATH=$PATH:$(go env GOPATH)/bin
          
          git clone https://github.com/IK-akx/pharmacy-proto.git proto-repo
          
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ github.repository }}
          fi

          # Генерируем файлы в режиме source_relative
          protoc --proto_path=proto-repo \
            --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            proto-repo/order/order.proto \
            proto-repo/product/product.proto \
            proto-repo/user/user.proto

          # Копируем сгенерированные папки с кодом в корень репозитория
          cp -r proto-repo/order/ .
          cp -r proto-repo/product/ .
          cp -r proto-repo/user/ .
